server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
  port: 8080
  servlet:
    context-path: /healthcare-services/api

spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/healthcareservices
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 15MB

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

backendapi:
  app:
    jwtSecret: healthcareServicesSecretKey
    jwtExpirationMs: 86400000
